version: '3'
services:
  node-stdlib-api-server:
    build: ./
    ports:
      - "${LOCALHOST_API_PORT}:${CONTAINER_API_PORT}" # enclosed by \"\" as expected by standard library parsing method
    volumes:
      - ./:/api
    environment:
      - LOCALHOST_API_PORT=${LOCALHOST_API_PORT}
      - CONTAINER_API_PORT=${CONTAINER_API_PORT}